steps:

#build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dev-pro', '.']

#push the docker image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dev-pro']

#deploy the container image to GKE
- name: 'gcr.io/cloud-builders-community/helm'
  args:
  - 'upgrade'
  - '--install'
  - 'dev-pro'
  - './helm'
  - '--namespace=dev-prod'
  - '--set=image.repository=gcr.io/$PROJECT_ID'
  - '--set=image.tag=dev-pro'

options:
  logging: CLOUD_LOGGING_ONLY
