apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-pro-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-pro-app
  template:
    metadata:
      labels:
        app: dev-pro-app
    spec:
      containers:
      - name: gke-dev-pro
        image: gcr.io/rosy-ratio-402707/dev-pro-dev:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: devpro-service
  namespace: dev-pro-dev
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP    
    port: 80
    targetPort: 5000
  selector:
    app: dev-pro-app
  type: LoadBalancer     
